# Uncomment the next line to define a global platform for your project
# platform:ios, '9.0'

target 'QYKitDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
#pod 'QYKit'
#  pod 'QYKit',:path => './QYKit'
pod 'PKHUD'
pod 'MJRefresh'
pod 'DZNEmptyDataSet'
pod 'SnapKit'
pod 'MBProgressHUD'
end
